# Install Ubuntu 20.04 LTS - Focal Fossa
FROM tensorflow/tensorflow

# Handle user-prompt for Ubuntu installation (time zone selection & keyboard)
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=America
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    apt-utils wget build-essential cmake git libssl-dev \
    software-properties-common

RUN add-apt-repository universe

# Install Dev Tools
RUN apt-get update --fix-missing && apt-get upgrade -y && apt-get install -y \
    libpython3-dev python3-pip

RUN python3 -m pip install --upgrade pip

RUN python3 -m pip install -U \
    opencv-python numpy scipy pandas streamlit