FROM nvidia/cuda:11.8.0-base-ubuntu22.04

# Handle user-prompt for Ubuntu installation (time zone selection & keyboard)
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=America
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install Basic Linux Dependencies
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    apt-utils curl wget build-essential \
    cmake git software-properties-common ninja-build \
    nano \
    openssh-server

# Install Python11 & Dependencies
RUN add-apt-repository universe
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    python3.11
RUN apt-get install python3.11-distutils -y
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3.11 get-pip.py
RUN apt-get install python3.11-venv

# Install ROS2 Tools
RUN apt-get update && apt-get install curl gnupg lsb-release -y
RUN curl -sSL \
    https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o \
    /usr/share/keyrings/ros-archive-keyring.gpg

RUN echo "deb \
    [arch=amd64 signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] \
    http://packages.ros.org/ros2/ubuntu jammy main" \
    | tee /etc/apt/sources.list.d/ros2.list \
    > /dev/null

RUN apt-get update --fix-missing && apt-get upgrade -y \
    && apt-get install -y \
    python3-rosdep libpython3-dev python3-pip \
    python3-colcon-common-extensions \
    python3-flake8 python3-pytest-cov python3-testresources \
    python3-rosdep python3-setuptools python3-vcstool \
    ros-humble-rmw-fastrtps-cpp \
    ros-humble-rmw-cyclonedds-cpp

RUN python3 -m pip install -U \
    argcomplete flake8-blind-except flake8-builtins flake8-class-newline \
    flake8-comprehensions flake8-deprecated flake8-docstrings flake8-import-order \
    flake8-quotes pytest-repeat pytest-rerunfailures pytest setuptools

# Install ROS itself
RUN apt-get install ros-humble-desktop -y

# Install gazebo
RUN sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list' \
    && wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
RUN apt update && apt-get install -y gz-garden

# Environment Setup
SHELL ["/bin/bash", "-c"]
RUN echo source /opt/ros/humble/setup.bash >> /root/.bashrc

# Setup Root ssh
RUN mkdir /var/run/sshd
RUN echo 'root:1234' | chpasswd
RUN echo PermitRootLogin yes >> /etc/ssh/sshd_config
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

# X11 forward over SSH (X11-ception!)
RUN echo X11DisplayOffset 10 >> /etc/ssh/sshd_config
RUN echo X11UseLocalhost no >> /etc/ssh/sshd_config 
RUN echo X11Forwarding yes >> /etc/ssh/sshd_config 

# Other commonly changed deps (added here to avoid invalidating cache when changed)
RUN rosdep init
RUN rosdep update

# Install Other compilers
RUN add-apt-repository ppa:ubuntu-toolchain-r/test
RUN apt update && apt install -y \
    gcc-12 clang-14

# We must start ssh on boot, since systemd works weird in docker     
ENTRYPOINT service ssh restart && bash
EXPOSE 22
