FROM nvidia/cuda:11.8.0-base-ubuntu22.04

# Handle user-prompt for Ubuntu installation (time zone selection & keyboard)
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=America
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Basic Linux Dependencies
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    apt-utils curl wget build-essential cmake git software-properties-common \
    nano clang-12 
