FROM nvidia/cuda:11.8.0-base-ubuntu22.04

# Handle user-prompt for Ubuntu installation (time zone selection & keyboard)
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=America
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Basic Linux Dependencies
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    apt-utils curl wget build-essential \
    cmake git software-properties-common \
    nano clang-12 

# Install Python11 & Dependencies
RUN add-apt-repository universe
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    python3.11
RUN apt-get install python3.11-distutils -y
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3.11 get-pip.py
RUN apt-get install python3.11-venv
RUN apt-get remove --purge python3-apt && apt-get autoremove