# Install Ubuntu 20.04 LTS - Focal Fossa
FROM nvidia/cuda:11.6.0-devel-ubuntu20.04

# Handle user-prompt for Ubuntu installation (time zone selection & keyboard)
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=America
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    apt-utils curl wget build-essential cmake git software-properties-common

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    clang-12

RUN add-apt-repository universe
RUN add-apt-repository ppa:deadsnakes/ppa

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    python3.10

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 2

RUN apt-get remove python3.8 -y && apt-get autoremove -y
RUN apt-get install python3.10-distutils -y

RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3.10 get-pip.py
RUN apt-get install python3.10-venv

RUN apt-get remove --purge python3-apt && apt-get autoremove

RUN apt-get update && apt-get install curl gnupg lsb-release -y
RUN curl -sSL \
    https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o \
    /usr/share/keyrings/ros-archive-keyring.gpg

RUN echo "deb \
    [arch=amd64 signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] \
    http://packages.ros.org/ros2/ubuntu focal main" \
    | tee /etc/apt/sources.list.d/ros2.list \
    > /dev/null

# Install Dev Tools & ROS2 Tools
RUN apt-get update --fix-missing && apt-get upgrade -y && apt-get install -y \
    python3-rosdep libpython3-dev python3-pip \
    python3-colcon-common-extensions \
    python3-flake8 python3-pytest-cov python3-testresources \
    python3-rosdep python3-setuptools python3-vcstool \
    ros-rolling-rmw-fastrtps-cpp \
    ros-rolling-rmw-cyclonedds-cpp

RUN python3 -m pip install -U \
    argcomplete flake8-blind-except flake8-builtins flake8-class-newline \
    flake8-comprehensions flake8-deprecated flake8-docstrings flake8-import-order \
    flake8-quotes pytest-repeat pytest-rerunfailures pytest setuptools


ENV ROS2_PATH /opt/ros2_rolling
RUN mkdir -p $ROS2_PATH/src
WORKDIR $ROS2_PATH
RUN wget https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos
RUN vcs import src < ros2.repos

RUN rosdep init
RUN rosdep update
RUN rosdep install --from-paths src --ignore-src -y --skip-keys "fastcdr rti-connext-dds-5.3.1 urdfdom_headers"

WORKDIR $ROS2_PATH
RUN colcon build --symlink-install

# Environment Setup
SHELL ["/bin/bash", "-c"]
RUN . $ROS2_PATH/install/local_setup.bash
RUN source /opt/ros/rolling/setup.bash

# ------ Setting up Gazebo ------
RUN mkdir $ROS2_PATH/gazebo
WORKDIR $ROS2_PATH/gazebo
RUN curl -sSL http://get.gazebosim.org | sh

RUN apt-get update --fix-missing && apt-get upgrade -y && apt-get install -y \
    ros-rolling-gazebo-ros-pkgs ros-rolling-ros-core ros-rolling-geometry2

RUN source /opt/ros/rolling/setup.bash